markdown: rdiscount
pygments: true
permalink: /posts/:title
rdiscount:
  extensions: [smart]
title : Derek Stavis 
production_url : http://derekstavis.github.io
description: "Discoverings, thoughts, ideas and a bunch o geek-ish things"
disqus_shortname: derekstavis-blog
analytics: UA-37796108-1
gauges: 52516e05f5a1f54e81000100
author :
  name : Derek Willian Stavis
  github : derekstavis
  twitter : derekstavis
  email: dekestavis0@gmail.com
